/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package alquilervehiculos.Interface;
import alquilervehiculos.Utilidades.*;
import alquilervehiculos.controlador.*;
import alquilervehiculos.controlador.GestionUsuario;
import alquilervehiculos.excepciones.VehiculosExcepcion;
import alquilervehiculos.modelo.*;
import alquilervehiculos.modelo.Moto;
import java.beans.PropertyVetoException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sun.util.logging.PlatformLogger;

/**
 *
 * @author pavilion
 */
public class MdiVehiculos extends javax.swing.JFrame {
   GestionUsuario gestionUsuario;
   private Usuario usuarioAutenticado;
   GestionVehiculo gestionVehiculo;
   private LeerArchivoPlano leer;
    /**
     * Creates new form MdiVehiculos
     */
    public MdiVehiculos() {
        initComponents();
        gestionVehiculo = new GestionVehiculo();
        gestionUsuario = new GestionUsuario();
        
        
    }
    private void iniciarMenus(boolean estado) {
        mnuCrearUsuarios.setVisible(estado);
        mnuListarUsuarios.setVisible(estado);
        mnuVehiculos.setVisible(estado);
        mnuListaMotos.setVisible(estado);
        mnuListaCoches.setVisible(estado);
        mnuVehiculos.setVisible(estado);
        mnuListaFurgonetas.setVisible(estado);
    }

    private void gestionarPermisosMenu() {

        switch (usuarioAutenticado.getTipoUsuario().getCodigo()) {
            //administrador
            case "1":
                iniciarMenus(true);
                break;
            ///usuario
            case "2":
                iniciarMenus(false);
                mnuListarUsuarios.setVisible(true);
                mnuVehiculos.setVisible(true);
                mnuListaMotos.setVisible(true);
                mnuListaCoches.setVisible(true);
                mnuListaFurgonetas.setVisible(true);
                break;
            ///cliente
            case "3":
                iniciarMenus(false);
                mnuListarUsuarios.setVisible(true);
                mnuVehiculos.setVisible(true);
                mnuListaMotos.setVisible(true);
                mnuListaFurgonetas.setVisible(true);
                mnuCrearUsuarios.setVisible(true);
                break;
        }
    }
        

    public void validarCrearVehiculo () {

        if (jcbCVMoto.isSelected())
        {
            jcbCVCasco.setEnabled(true);
        }
        else
        {
            jcbCVCasco.setEnabled(false);
        }
        if (jcbCVCoche.isSelected())
        {
            jcbCVExtras.setEnabled(true);
        }
        else
        {
            jcbCVExtras.setEnabled(false);
        }
        if (jcbCVFutgo.isSelected())
        {
            spnCVCapFurg.setEnabled(true);
        }
        else
        {
            spnCVCapFurg.setEnabled(false);
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jifLogin = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        txtContrasenia = new javax.swing.JPasswordField();
        btnIngresar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jifUsuarios = new javax.swing.JInternalFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsuarios = new javax.swing.JTable();
        btnDescargarUsuariosPDF = new javax.swing.JButton();
        jifMotos = new javax.swing.JInternalFrame();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMotos = new javax.swing.JTable();
        jifCoches = new javax.swing.JInternalFrame();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblCoches = new javax.swing.JTable();
        jifFurgonetas = new javax.swing.JInternalFrame();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblFurgonetas = new javax.swing.JTable();
        jifListadoGeneralVehiculos = new javax.swing.JInternalFrame();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbListadoGeneral = new javax.swing.JTable();
        jifAlquilar = new javax.swing.JInternalFrame();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblCliente = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtClienteSeleccionado = new javax.swing.JTextPane();
        btnAlquilar = new javax.swing.JButton();
        txtMatriculaSelec = new javax.swing.JTextField();
        label19 = new java.awt.Label();
        label20 = new java.awt.Label();
        jDateEntregaAlquiler = new com.toedter.calendar.JDateChooser();
        jDateDevolucionAlquiler = new com.toedter.calendar.JDateChooser();
        label21 = new java.awt.Label();
        label22 = new java.awt.Label();
        txtOpcionesExtras = new javax.swing.JTextField();
        btnCalcularAlquiler = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jifmVehiculosAlquilados = new javax.swing.JInternalFrame();
        jScrollPane9 = new javax.swing.JScrollPane();
        tblVehiculosAlquilados = new javax.swing.JTable();
        jifCrearVehiculo = new javax.swing.JInternalFrame();
        txtCVMatricula = new javax.swing.JTextField();
        label3 = new java.awt.Label();
        txtCVKm = new javax.swing.JTextField();
        label6 = new java.awt.Label();
        label10 = new java.awt.Label();
        jcbCVExtras = new javax.swing.JCheckBox();
        jcbCVCasco = new javax.swing.JCheckBox();
        spnCVCapFurg = new javax.swing.JSpinner();
        label11 = new java.awt.Label();
        btnCVCrearVehiculo = new javax.swing.JButton();
        jcbCVCoche = new javax.swing.JCheckBox();
        jcbCVMoto = new javax.swing.JCheckBox();
        jcbCVFutgo = new javax.swing.JCheckBox();
        label12 = new java.awt.Label();
        jScrollPane10 = new javax.swing.JScrollPane();
        txtCVValorAlquiler = new javax.swing.JTextPane();
        jLabel5 = new javax.swing.JLabel();
        jcbDistponible = new javax.swing.JCheckBox();
        label9 = new java.awt.Label();
        jifCrearUsuario = new javax.swing.JInternalFrame();
        txtCUNombre = new javax.swing.JTextField();
        txtCUIdentificacion = new javax.swing.JTextField();
        txtCUCorreoElectronico = new javax.swing.JTextField();
        txtCUContrasenia = new javax.swing.JTextField();
        cboxTipoUsuario = new javax.swing.JComboBox<>();
        lblName = new java.awt.Label();
        label4 = new java.awt.Label();
        label5 = new java.awt.Label();
        label7 = new java.awt.Label();
        label8 = new java.awt.Label();
        btnCrearUsr = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        mnuArchivo = new javax.swing.JMenu();
        mnuCrearUsuarios = new javax.swing.JMenuItem();
        mnuListarUsuarios = new javax.swing.JMenuItem();
        mnuDescargarVehiculos = new javax.swing.JMenuItem();
        mnuVehiculosAlquilados = new javax.swing.JMenuItem();
        mnuVehiculos = new javax.swing.JMenu();
        mnuCrearVehiculo = new javax.swing.JMenuItem();
        mnuListaMotos = new javax.swing.JMenuItem();
        mnuListaCoches = new javax.swing.JMenuItem();
        mnuListaFurgonetas = new javax.swing.JMenuItem();
        mnuAlquilarVehiculo = new javax.swing.JMenuItem();
        mnuCerrarSesion = new javax.swing.JMenuItem();
        mnuSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jifLogin.setTitle("Login");
        jifLogin.setVisible(true);

        jLabel1.setText("*Correo electronico");

        jLabel2.setText("*Contraseña");

        txtContrasenia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContraseniaActionPerformed(evt);
            }
        });

        btnIngresar.setBackground(new java.awt.Color(0, 51, 204));
        btnIngresar.setForeground(new java.awt.Color(255, 255, 255));
        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("---------------------------------------------------------------------------");

        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("¿No estas registrado?");

        jButton1.setBackground(new java.awt.Color(0, 0, 255));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Registrate!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jifLoginLayout = new javax.swing.GroupLayout(jifLogin.getContentPane());
        jifLogin.getContentPane().setLayout(jifLoginLayout);
        jifLoginLayout.setHorizontalGroup(
            jifLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jifLoginLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jifLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jifLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtContrasenia, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                    .addComponent(txtCorreo))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jifLoginLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jifLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jifLoginLayout.createSequentialGroup()
                        .addComponent(btnIngresar)
                        .addGap(208, 208, 208))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jifLoginLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(91, 91, 91))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jifLoginLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(192, 192, 192))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jifLoginLayout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(172, 172, 172))))
        );
        jifLoginLayout.setVerticalGroup(
            jifLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jifLoginLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jifLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jifLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnIngresar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        desktopPane.add(jifLogin);
        jifLogin.setBounds(60, 50, 530, 320);

        jifUsuarios.setClosable(true);
        jifUsuarios.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jifUsuarios.setIconifiable(true);
        jifUsuarios.setMaximizable(true);
        jifUsuarios.setResizable(true);
        jifUsuarios.setTitle("Lista usuarios");
        jifUsuarios.setVisible(false);

        tblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Cedula", "Nombre", "Usuario"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblUsuarios);

        btnDescargarUsuariosPDF.setText("Descargar Lista usuarios");
        btnDescargarUsuariosPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescargarUsuariosPDFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jifUsuariosLayout = new javax.swing.GroupLayout(jifUsuarios.getContentPane());
        jifUsuarios.getContentPane().setLayout(jifUsuariosLayout);
        jifUsuariosLayout.setHorizontalGroup(
            jifUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jifUsuariosLayout.createSequentialGroup()
                .addGroup(jifUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jifUsuariosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jifUsuariosLayout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(btnDescargarUsuariosPDF)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jifUsuariosLayout.setVerticalGroup(
            jifUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jifUsuariosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDescargarUsuariosPDF, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        desktopPane.add(jifUsuarios);
        jifUsuarios.setBounds(150, 10, 430, 430);

        jifMotos.setClosable(true);
        jifMotos.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jifMotos.setIconifiable(true);
        jifMotos.setMaximizable(true);
        jifMotos.setResizable(true);
        jifMotos.setTitle("Lista de motos");
        jifMotos.setMaximumSize(new java.awt.Dimension(2147483641, 2147483641));
        jifMotos.setVisible(false);

        tblMotos.setAutoCreateRowSorter(true);
        tblMotos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null,  new Boolean(true), null,  new Boolean(true)},
                {null, null,  new Boolean(true), null,  new Boolean(false)},
                {null, null,  new Boolean(false), null,  new Boolean(false)},
                {null, null,  new Boolean(false), null,  new Boolean(false)}
            },
            new String [] {
                "Matricula", "Kilometraje", "Estado", "Valor de alquiler", "Casco"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Boolean.class, java.lang.Double.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblMotos);

        javax.swing.GroupLayout jifMotosLayout = new javax.swing.GroupLayout(jifMotos.getContentPane());
        jifMotos.getContentPane().setLayout(jifMotosLayout);
        jifMotosLayout.setHorizontalGroup(
            jifMotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jifMotosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jifMotosLayout.setVerticalGroup(
            jifMotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jifMotosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(257, Short.MAX_VALUE))
        );

        desktopPane.add(jifMotos);
        jifMotos.setBounds(30, 10, 300, 470);

        jifCoches.setClosable(true);
        jifCoches.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jifCoches.setIconifiable(true);
        jifCoches.setMaximizable(true);
        jifCoches.setResizable(true);
        jifCoches.setTitle("Listado de coches");
        jifCoches.setMinimumSize(new java.awt.Dimension(1189, 3456));
        jifCoches.setVisible(false);

        tblCoches.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null,  new Boolean(true), null,  new Boolean(false)},
                {null, null,  new Boolean(false), null, null},
                {null, null,  new Boolean(true), null, null},
                {null, null,  new Boolean(true), null,  new Boolean(true)}
            },
            new String [] {
                "Matricula", "Kilometraje", "Estado", "Valor de Alquiler", "Extras"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Boolean.class, java.lang.Double.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblCoches);

        javax.swing.GroupLayout jifCochesLayout = new javax.swing.GroupLayout(jifCoches.getContentPane());
        jifCoches.getContentPane().setLayout(jifCochesLayout);
        jifCochesLayout.setHorizontalGroup(
            jifCochesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jifCochesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );
        jifCochesLayout.setVerticalGroup(
            jifCochesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jifCochesLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        desktopPane.add(jifCoches);
        jifCoches.setBounds(240, 10, 380, 440);

        jifFurgonetas.setClosable(true);
        jifFurgonetas.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jifFurgonetas.setIconifiable(true);
        jifFurgonetas.setMaximizable(true);
        jifFurgonetas.setResizable(true);
        jifFurgonetas.setTitle("Lista de furgonetas");
        jifFurgonetas.setMaximumSize(new java.awt.Dimension(314748374, 314748374));
        jifFurgonetas.setMinimumSize(new java.awt.Dimension(300, 300));
        jifFurgonetas.setPreferredSize(new java.awt.Dimension(600, 600));
        jifFurgonetas.setVisible(false);

        tblFurgonetas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null,  new Boolean(true), null, null},
                {null, null,  new Boolean(true), null, null},
                {null, null,  new Boolean(true), null, null}
            },
            new String [] {
                "Matricula", "Kilometraje", "Estado", "Valor de alquiler", "Capacidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Boolean.class, java.lang.Double.class, java.lang.Short.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tblFurgonetas);

        javax.swing.GroupLayout jifFurgonetasLayout = new javax.swing.GroupLayout(jifFurgonetas.getContentPane());
        jifFurgonetas.getContentPane().setLayout(jifFurgonetasLayout);
        jifFurgonetasLayout.setHorizontalGroup(
            jifFurgonetasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jifFurgonetasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jifFurgonetasLayout.setVerticalGroup(
            jifFurgonetasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jifFurgonetasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        desktopPane.add(jifFurgonetas);
        jifFurgonetas.setBounds(130, 10, 420, 450);

        jifListadoGeneralVehiculos.setClosable(true);
        jifListadoGeneralVehiculos.setIconifiable(true);
        jifListadoGeneralVehiculos.setMaximizable(true);
        jifListadoGeneralVehiculos.setResizable(true);
        jifListadoGeneralVehiculos.setTitle("Listado general de vehiculos");
        jifListadoGeneralVehiculos.setVisible(false);

        tbListadoGeneral.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Matricula", "Kilometraje", "Estado", "ValorAlquiler"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Boolean.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tbListadoGeneral);

        javax.swing.GroupLayout jifListadoGeneralVehiculosLayout = new javax.swing.GroupLayout(jifListadoGeneralVehiculos.getContentPane());
        jifListadoGeneralVehiculos.getContentPane().setLayout(jifListadoGeneralVehiculosLayout);
        jifListadoGeneralVehiculosLayout.setHorizontalGroup(
            jifListadoGeneralVehiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jifListadoGeneralVehiculosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jifListadoGeneralVehiculosLayout.setVerticalGroup(
            jifListadoGeneralVehiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jifListadoGeneralVehiculosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        desktopPane.add(jifListadoGeneralVehiculos);
        jifListadoGeneralVehiculos.setBounds(200, 10, 370, 430);

        jifAlquilar.setClosable(true);
        jifAlquilar.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jifAlquilar.setIconifiable(true);
        jifAlquilar.setMaximizable(true);
        jifAlquilar.setResizable(true);
        jifAlquilar.setTitle("Alquilar Vehículo");
        jifAlquilar.setVisible(false);

        tblCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Tipo de Usuario", "Identificacion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblClienteMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(tblCliente);

        jScrollPane7.setViewportView(txtClienteSeleccionado);

        btnAlquilar.setText("Alquilar");
        btnAlquilar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlquilarActionPerformed(evt);
            }
        });

        txtMatriculaSelec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMatriculaSelecActionPerformed(evt);
            }
        });
        txtMatriculaSelec.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMatriculaSelecKeyTyped(evt);
            }
        });

        label19.setText("Cliente");

        label20.setText("Vehículo");

        jDateDevolucionAlquiler.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jDateDevolucionAlquilerMouseClicked(evt);
            }
        });

        label21.setText("Fecha entrega");

        label22.setText("Fecha devolución");

        btnCalcularAlquiler.setText("Calcular Alquiler");
        btnCalcularAlquiler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularAlquilerActionPerformed(evt);
            }
        });

        jLabel3.setText("Clientes");

        javax.swing.GroupLayout jifAlquilarLayout = new javax.swing.GroupLayout(jifAlquilar.getContentPane());
        jifAlquilar.getContentPane().setLayout(jifAlquilarLayout);
        jifAlquilarLayout.setHorizontalGroup(
            jifAlquilarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jifAlquilarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jifAlquilarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jifAlquilarLayout.createSequentialGroup()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addGroup(jifAlquilarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateDevolucionAlquiler, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMatriculaSelec, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtOpcionesExtras, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label19, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCalcularAlquiler)
                            .addGroup(jifAlquilarLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(btnAlquilar))
                            .addComponent(jDateEntregaAlquiler, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jifAlquilarLayout.setVerticalGroup(
            jifAlquilarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jifAlquilarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jifAlquilarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jifAlquilarLayout.createSequentialGroup()
                        .addComponent(label19, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(label20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtMatriculaSelec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(txtOpcionesExtras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(label21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateEntregaAlquiler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateDevolucionAlquiler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(btnCalcularAlquiler)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAlquilar))
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        desktopPane.add(jifAlquilar);
        jifAlquilar.setBounds(50, 20, 450, 360);

        jifmVehiculosAlquilados.setClosable(true);
        jifmVehiculosAlquilados.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jifmVehiculosAlquilados.setIconifiable(true);
        jifmVehiculosAlquilados.setMaximizable(true);
        jifmVehiculosAlquilados.setResizable(true);
        jifmVehiculosAlquilados.setTitle("Vehículos Alquilados");
        jifmVehiculosAlquilados.setVisible(false);

        tblVehiculosAlquilados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Vehículo", "Cliente", "Fecha Entrega", "Fecha Devolución"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane9.setViewportView(tblVehiculosAlquilados);

        javax.swing.GroupLayout jifmVehiculosAlquiladosLayout = new javax.swing.GroupLayout(jifmVehiculosAlquilados.getContentPane());
        jifmVehiculosAlquilados.getContentPane().setLayout(jifmVehiculosAlquiladosLayout);
        jifmVehiculosAlquiladosLayout.setHorizontalGroup(
            jifmVehiculosAlquiladosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jifmVehiculosAlquiladosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                .addContainerGap())
        );
        jifmVehiculosAlquiladosLayout.setVerticalGroup(
            jifmVehiculosAlquiladosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jifmVehiculosAlquiladosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        desktopPane.add(jifmVehiculosAlquilados);
        jifmVehiculosAlquilados.setBounds(20, 10, 380, 320);

        jifCrearVehiculo.setClosable(true);
        jifCrearVehiculo.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jifCrearVehiculo.setIconifiable(true);
        jifCrearVehiculo.setMaximizable(true);
        jifCrearVehiculo.setResizable(true);
        jifCrearVehiculo.setTitle("Crear vehiculo");
        jifCrearVehiculo.setVisible(false);

        txtCVMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCVMatriculaActionPerformed(evt);
            }
        });

        label3.setText("Matricula");

        txtCVKm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCVKmActionPerformed(evt);
            }
        });

        label6.setText("Kilometraje");

        label10.setText("Tipo de vehiculo");

        jcbCVExtras.setText("Extras Coche");
        jcbCVExtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbCVExtrasActionPerformed(evt);
            }
        });

        jcbCVCasco.setText("Casco Moto");
        jcbCVCasco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbCVCascoActionPerformed(evt);
            }
        });

        spnCVCapFurg.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnCVCapFurgStateChanged(evt);
            }
        });

        label11.setText("Capacidad Furgoneta");

        btnCVCrearVehiculo.setText("Crear Vehiculo");
        btnCVCrearVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCVCrearVehiculoActionPerformed(evt);
            }
        });

        jcbCVCoche.setText("Coche");
        jcbCVCoche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbCVCocheActionPerformed(evt);
            }
        });

        jcbCVMoto.setText("Moto");
        jcbCVMoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbCVMotoActionPerformed(evt);
            }
        });

        jcbCVFutgo.setText("Furgoneta");
        jcbCVFutgo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbCVFutgoActionPerformed(evt);
            }
        });

        label12.setText("Valor Alquiler");

        jScrollPane10.setViewportView(txtCVValorAlquiler);

        jLabel5.setText("Otras Opciones");

        jcbDistponible.setText("Disponible");

        label9.setText("Disponibilidad");

        javax.swing.GroupLayout jifCrearVehiculoLayout = new javax.swing.GroupLayout(jifCrearVehiculo.getContentPane());
        jifCrearVehiculo.getContentPane().setLayout(jifCrearVehiculoLayout);
        jifCrearVehiculoLayout.setHorizontalGroup(
            jifCrearVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jifCrearVehiculoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jifCrearVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jifCrearVehiculoLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btnCVCrearVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addGroup(jifCrearVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbCVCasco)
                            .addComponent(jcbCVExtras))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jifCrearVehiculoLayout.createSequentialGroup()
                        .addGroup(jifCrearVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jifCrearVehiculoLayout.createSequentialGroup()
                                .addGroup(jifCrearVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(jifCrearVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCVKm, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                                    .addComponent(txtCVMatricula))
                                .addGap(47, 47, 47)
                                .addGroup(jifCrearVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jifCrearVehiculoLayout.createSequentialGroup()
                                        .addGroup(jifCrearVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jifCrearVehiculoLayout.createSequentialGroup()
                                                .addComponent(jcbCVCoche)
                                                .addGap(18, 18, 18)
                                                .addComponent(jcbCVMoto))
                                            .addComponent(jLabel5))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jifCrearVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jcbCVFutgo)
                                            .addGroup(jifCrearVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(jifCrearVehiculoLayout.createSequentialGroup()
                                                    .addGap(33, 33, 33)
                                                    .addGroup(jifCrearVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jcbDistponible)
                                                        .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGroup(jifCrearVehiculoLayout.createSequentialGroup()
                                                    .addComponent(label11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(spnCVCapFurg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                            .addGroup(jifCrearVehiculoLayout.createSequentialGroup()
                                .addComponent(label12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jifCrearVehiculoLayout.setVerticalGroup(
            jifCrearVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jifCrearVehiculoLayout.createSequentialGroup()
                .addGroup(jifCrearVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jifCrearVehiculoLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jifCrearVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCVMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jifCrearVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jifCrearVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jcbCVCoche)
                                .addComponent(jcbCVMoto)
                                .addComponent(jcbCVFutgo))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jifCrearVehiculoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtCVKm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jifCrearVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jifCrearVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jifCrearVehiculoLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jifCrearVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jifCrearVehiculoLayout.createSequentialGroup()
                                .addComponent(jcbCVExtras)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcbCVCasco))
                            .addComponent(btnCVCrearVehiculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jifCrearVehiculoLayout.createSequentialGroup()
                        .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbDistponible)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jifCrearVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spnCVCapFurg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(106, Short.MAX_VALUE))
        );

        desktopPane.add(jifCrearVehiculo);
        jifCrearVehiculo.setBounds(60, 40, 420, 340);

        jifCrearUsuario.setClosable(true);
        jifCrearUsuario.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jifCrearUsuario.setIconifiable(true);
        jifCrearUsuario.setMaximizable(true);
        jifCrearUsuario.setResizable(true);
        jifCrearUsuario.setTitle("Crear usuario");
        jifCrearUsuario.setVisible(false);

        txtCUIdentificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCUIdentificacionActionPerformed(evt);
            }
        });

        cboxTipoUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Usuario", "Cliente", " ", " ", " " }));
        cboxTipoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxTipoUsuarioActionPerformed(evt);
            }
        });

        lblName.setText("Nombre");

        label4.setText("Identificación");

        label5.setText("Correo Electronico");

        label7.setText("Tipo de usuario");

        label8.setText("Contraseña");

        btnCrearUsr.setText("Crear usuario");
        btnCrearUsr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearUsrActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jifCrearUsuarioLayout = new javax.swing.GroupLayout(jifCrearUsuario.getContentPane());
        jifCrearUsuario.getContentPane().setLayout(jifCrearUsuarioLayout);
        jifCrearUsuarioLayout.setHorizontalGroup(
            jifCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jifCrearUsuarioLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jifCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jifCrearUsuarioLayout.createSequentialGroup()
                        .addGroup(jifCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jifCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jifCrearUsuarioLayout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(cboxTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnCrearUsr))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jifCrearUsuarioLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jifCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCUIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCUNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(42, 42, 42))))
                    .addGroup(jifCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jifCrearUsuarioLayout.createSequentialGroup()
                            .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCUContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jifCrearUsuarioLayout.createSequentialGroup()
                            .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtCUCorreoElectronico, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jifCrearUsuarioLayout.setVerticalGroup(
            jifCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jifCrearUsuarioLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jifCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCUCorreoElectronico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jifCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCUContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jifCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jifCrearUsuarioLayout.createSequentialGroup()
                        .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jifCrearUsuarioLayout.createSequentialGroup()
                        .addComponent(txtCUNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtCUIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(48, 48, 48)
                .addGroup(jifCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jifCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cboxTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCrearUsr)))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        desktopPane.add(jifCrearUsuario);
        jifCrearUsuario.setBounds(10, 10, 220, 280);

        mnuArchivo.setMnemonic('f');
        mnuArchivo.setText("Archivo");

        mnuCrearUsuarios.setMnemonic('o');
        mnuCrearUsuarios.setText("Iniciar sesion");
        mnuCrearUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCrearUsuariosActionPerformed(evt);
            }
        });
        mnuArchivo.add(mnuCrearUsuarios);

        mnuListarUsuarios.setMnemonic('s');
        mnuListarUsuarios.setText("Listar usuario");
        mnuListarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuListarUsuariosActionPerformed(evt);
            }
        });
        mnuArchivo.add(mnuListarUsuarios);

        mnuDescargarVehiculos.setText("Descargar lista todos los vehiculos");
        mnuDescargarVehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDescargarVehiculosActionPerformed(evt);
            }
        });
        mnuArchivo.add(mnuDescargarVehiculos);

        mnuVehiculosAlquilados.setText("Vehiculos Alquilados");
        mnuVehiculosAlquilados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuVehiculosAlquiladosActionPerformed(evt);
            }
        });
        mnuArchivo.add(mnuVehiculosAlquilados);

        mnuVehiculos.setText("Vehiculos");

        mnuCrearVehiculo.setText("Crear vehiculo");
        mnuCrearVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCrearVehiculoActionPerformed(evt);
            }
        });
        mnuVehiculos.add(mnuCrearVehiculo);

        mnuListaMotos.setText("Lista Motos");
        mnuListaMotos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuListaMotosActionPerformed(evt);
            }
        });
        mnuVehiculos.add(mnuListaMotos);

        mnuListaCoches.setText("Lista Coches");
        mnuListaCoches.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuListaCochesActionPerformed(evt);
            }
        });
        mnuVehiculos.add(mnuListaCoches);

        mnuListaFurgonetas.setText("Lista Furgonetas");
        mnuListaFurgonetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuListaFurgonetasActionPerformed(evt);
            }
        });
        mnuVehiculos.add(mnuListaFurgonetas);

        mnuAlquilarVehiculo.setText("Alquilar Vehiculo");
        mnuAlquilarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAlquilarVehiculoActionPerformed(evt);
            }
        });
        mnuVehiculos.add(mnuAlquilarVehiculo);

        mnuArchivo.add(mnuVehiculos);

        mnuCerrarSesion.setMnemonic('a');
        mnuCerrarSesion.setText("Cerrar sesion");
        mnuCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCerrarSesionActionPerformed(evt);
            }
        });
        mnuArchivo.add(mnuCerrarSesion);

        mnuSalir.setMnemonic('x');
        mnuSalir.setText("salir");
        mnuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSalirActionPerformed(evt);
            }
        });
        mnuArchivo.add(mnuSalir);

        menuBar.add(mnuArchivo);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 633, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnuSalirActionPerformed
    private void llenarTablaClientes() {
        DefaultTableModel model = (DefaultTableModel) tblCliente.getModel();
        model.getDataVector().removeAllElements();
        for (Cliente cliente : gestionUsuario.getClientes())
        {
            model.addRow(cliente.obtenerArregloClientes());
        }
        tblCliente.setModel(model);

    }
    private void pintarUsuarios (){
        DefaultTableModel model = (DefaultTableModel) tblUsuarios.getModel();
        model.getDataVector().removeAllElements();
        for ( Usuario usuario: gestionUsuario.getUsuarios()){
            model.addRow(usuario.obtenerArregloObjeto());
        }
        tblUsuarios.setModel(model);
    }
    private void llenarMotos (){
        DefaultTableModel model = (DefaultTableModel) tblMotos.getModel();
        model.getDataVector().removeAllElements();
        for (AbstractVehiculo moto: gestionVehiculo.obtenerVehiculo("Moto"))
        {
            model.addRow(moto.obtenerArregloVehiculos());
        }
        tblCoches.setModel(model);
    }
    private void llenarCoches (){
        DefaultTableModel model = (DefaultTableModel) tblCoches.getModel();
        model.getDataVector().removeAllElements();
        for (AbstractVehiculo coche : gestionVehiculo.obtenerVehiculo("Coche")){
            model.addRow(coche.obtenerArregloVehiculos());
        }
        tblCoches.setModel(model);
    }
    private void llenarFurgonetas (){
        DefaultTableModel model = (DefaultTableModel) tblFurgonetas.getModel();
        model.getDataVector().removeAllElements();
        for (AbstractVehiculo furgoneta : gestionVehiculo.obtenerVehiculo("Furgoneta")){
            model.addRow(furgoneta.obtenerArregloVehiculos());
        }
        tblFurgonetas.setModel(model);
    }
   

     private void llenarVehiculosAlquilados()
    {
        DefaultTableModel model = (DefaultTableModel) tblVehiculosAlquilados.getModel();
        model.getDataVector().removeAllElements();
        for (AlquilaVehiculo vehiculo : gestionVehiculo.getVehiculosAlquilados())
        {
            model.addRow(vehiculo.obtenerArregloVehiculoAlquilar());

        }
        tblVehiculosAlquilados.setModel(model);

    }
   
    
    private void mnuListarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuListarUsuariosActionPerformed
      gestionUsuario.llenarUsuarios();
      pintarUsuarios();
      jifUsuarios.repaint();
      jifUsuarios.show();
      if(jifUsuarios.isIcon()){
          try {
              jifUsuarios.setMaximum(true);
          } catch (PropertyVetoException ex){
              Logger.getLogger(MdiVehiculos.class.getName()).log(Level.SEVERE, null, ex);
          }
      }
    }//GEN-LAST:event_mnuListarUsuariosActionPerformed
    
    private void mnuListaMotosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuListaMotosActionPerformed
          // TODO add your handling code here:
        gestionVehiculo.llenarVehiculos();
        llenarMotos();
        jifMotos.repaint();
        jifMotos.show();

        if (jifMotos.isIcon())
        {
            try
            {
                jifMotos.setMaximum(true);
            }
            catch (PropertyVetoException ex)
            {
                Logger.getLogger(MdiVehiculos.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_mnuListaMotosActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        // TODO add your handling code here:
           if(txtCorreo.getText() == null || txtCorreo.getText().compareTo("") == 0 ) {
            JOptionPane.showMessageDialog(this,
                "Debe diligenciar el correo", "Datos Faltantes", 2);
        } else if (txtContrasenia.getPassword().length == 0) {
            JOptionPane.showMessageDialog(this,
                "Debe diligenciar la contraseña", "Datos Faltantes", 2);
        } else {
            gestionUsuario = new GestionUsuario();

            //Significa que diligencio correo y contraseña
            Pattern pattern = Pattern.compile("^[a-zA-Z0-9_!#$%&'*+/=?`{|}~^.-]+@[a-zA-Z0-9.-]+$");
            Matcher matcher = pattern.matcher(txtCorreo.getText());
            
            

            if (matcher.find() == true) {
                usuarioAutenticado = gestionUsuario.
                validarUsuario(txtCorreo.getText(), txtContrasenia.getText());
                if (usuarioAutenticado == null) {
                    JOptionPane.showMessageDialog(this,
                        "El usuario Ingresado no existe", "Datos Erróneos", 0);
                } else {
                    gestionUsuario = new GestionUsuario();
                    gestionVehiculo = new GestionVehiculo(null);
                    String nombreUsr = usuarioAutenticado.getNombre().toUpperCase();

                    JOptionPane.showMessageDialog(this,
                            "Bienvenido " + nombreUsr, "Bienvenido", 1);
                    mnuVehiculos.setEnabled(true);
                    //gestionarPermisosMenu();
                    jifLogin.hide();
                }
            } else {
                JOptionPane.showMessageDialog(this,
                    "El correo no tiene un formato válido", "Datos Erróneos", 0);

            }

        }
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void txtContraseniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContraseniaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContraseniaActionPerformed

    private void mnuCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCerrarSesionActionPerformed
 mnuArchivo.setEnabled(false);
        txtCorreo.setText("");
        txtContrasenia.setText("");
        usuarioAutenticado = null;
        iniciarMenus(false);
        jifLogin.show();        // TODO add your handling code here:
    }//GEN-LAST:event_mnuCerrarSesionActionPerformed

    private void mnuCrearUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCrearUsuariosActionPerformed
        // TODO add your handling code here:
        jifLogin.show();
    }//GEN-LAST:event_mnuCrearUsuariosActionPerformed

    private void mnuListaCochesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuListaCochesActionPerformed
        // TODO add your handling code here:
          gestionVehiculo.llenarVehiculos();
        llenarCoches();
        jifCoches.repaint();
        jifCoches.show();

        if (jifCoches.isIcon())
        {
            try
            {
                jifCoches.setMaximum(true);
            }
            catch (PropertyVetoException ex)
            {
                Logger.getLogger(MdiVehiculos.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_mnuListaCochesActionPerformed
     
    private void mnuListaFurgonetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuListaFurgonetasActionPerformed
        // TODO add your handling code here:
        gestionVehiculo.llenarVehiculos();
        llenarFurgonetas();
        jifFurgonetas.repaint();
        jifFurgonetas.show();

        if (jifFurgonetas.isIcon())
        {
            try
            {
                jifFurgonetas.setMaximum(true);
            }
            catch (PropertyVetoException ex)
            {
                Logger.getLogger(MdiVehiculos.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
      
    }//GEN-LAST:event_mnuListaFurgonetasActionPerformed

    private void tblClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblClienteMouseClicked
        // TODO add your handling code here:
        int seleccionado = tblCliente.rowAtPoint(evt.getPoint());
        txtClienteSeleccionado.setText(String.valueOf(tblCliente.getValueAt(seleccionado, 0)));
    }//GEN-LAST:event_tblClienteMouseClicked

    private void btnAlquilarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlquilarActionPerformed

        if (txtClienteSeleccionado.getText() == null || txtClienteSeleccionado.getText().compareTo("") == 0)
        {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un cliente");
        }
        else if (txtMatriculaSelec.getText() == null || txtMatriculaSelec.getText().compareTo("") == 0)
        {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un vehículo");
        }
        else if (jDateEntregaAlquiler.getDate() == null)
        {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una fecha de entrega");
        }
        else if (jDateDevolucionAlquiler.getDate() == null)
        {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una fecha de devolución");
        }
        else if (jDateEntregaAlquiler.getDate().compareTo(jDateDevolucionAlquiler.getDate()) > 0)
        {
            JOptionPane.showMessageDialog(this, "La fecha de devolucion es anterior a la fecha de alquiler");
        }
        else
        {

            if (gestionVehiculo.buscarVehiculo(txtMatriculaSelec.getText()).isEstado() == false)
            {

                JOptionPane.showMessageDialog(this, "El vehículo de matricula " + txtMatriculaSelec.getText()
                    + " se encuentra ocupado");
                txtMatriculaSelec.setText("");
            }
            else
            {

                AlquilaVehiculo alquilado = new AlquilaVehiculo(gestionVehiculo.buscarVehiculo(txtMatriculaSelec.getText()),
                    jDateEntregaAlquiler.getDate(), jDateDevolucionAlquiler.getDate(),
                    gestionUsuario.encontrarCliente(txtClienteSeleccionado.getText()));

                try
                {

                    gestionVehiculo.buscarVehiculo(txtMatriculaSelec.getText()).alquilar();
                    gestionVehiculo.adicionarVehiculoAlquilado(alquilado);
                    llenarVehiculosAlquilados();
                    //llenarTablaDevolver();

                    JOptionPane.showMessageDialog(this, "El vehiculo " + txtMatriculaSelec.getText()
                        + " fue alquilado a " + txtClienteSeleccionado.getText());
                    txtMatriculaSelec.setText("");
                    txtClienteSeleccionado.setText("");

                }
                catch (VehiculosExcepcion ex)
                {
                    Logger.getLogger(MdiVehiculos.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        }
    }//GEN-LAST:event_btnAlquilarActionPerformed

    private void txtMatriculaSelecKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMatriculaSelecKeyTyped

    }//GEN-LAST:event_txtMatriculaSelecKeyTyped

    private void jDateDevolucionAlquilerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDateDevolucionAlquilerMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jDateDevolucionAlquilerMouseClicked

    private void btnCalcularAlquilerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularAlquilerActionPerformed
        if (txtMatriculaSelec.getText() == null || txtMatriculaSelec.getText().compareTo("") == 0)
        {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un vehículo");
        }
        else if (jDateEntregaAlquiler.getDate() == null)
        {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una fecha de entrega");
        }
        else if (jDateDevolucionAlquiler.getDate() == null)
        {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una fecha de devolución");
        }
        else if (jDateEntregaAlquiler.getDate().compareTo(jDateDevolucionAlquiler.getDate()) > 0)
        {
            JOptionPane.showMessageDialog(this, "La fecha de devolucion es anterior a la fecha de alquiler");
        }
        else
        {
            int dias = gestionVehiculo.calcularDias(jDateEntregaAlquiler.getCalendar(), jDateDevolucionAlquiler.getCalendar());
            AbstractVehiculo veh = gestionVehiculo.buscarVehiculo(txtMatriculaSelec.getText());
            double valor = veh.calcularAlquiler(dias);
            String mensaje = "El valor del vehículo " + veh.getMatricula() + " por " + dias + " días, es de " + valor;
            JOptionPane.showMessageDialog(this, mensaje);
        }
    }//GEN-LAST:event_btnCalcularAlquilerActionPerformed

    private void mnuVehiculosAlquiladosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuVehiculosAlquiladosActionPerformed
        // TODO add your handling code here:
         llenarVehiculosAlquilados();
        jifmVehiculosAlquilados.repaint();
        jifmVehiculosAlquilados.show();

        if (jifmVehiculosAlquilados.isIcon())
        {
            try
            {

                jifmVehiculosAlquilados.setMaximum(true);
            }
            catch (PropertyVetoException ex)
            {
                Logger.getLogger(MdiVehiculos.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_mnuVehiculosAlquiladosActionPerformed

    private void mnuAlquilarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAlquilarVehiculoActionPerformed
        // TODO add your handling code here:
        gestionUsuario.llenarClientes();
        gestionVehiculo.llenarVehiculos();
        llenarTablaClientes();
        jifAlquilar.repaint();
        jifAlquilar.show();

        if (jifAlquilar.isIcon())
        {
            try
            {

                jifAlquilar.setMaximum(true);
            }
            catch (PropertyVetoException ex)
            {
                Logger.getLogger(MdiVehiculos.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_mnuAlquilarVehiculoActionPerformed

    private void txtMatriculaSelecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMatriculaSelecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMatriculaSelecActionPerformed

    private void mnuCrearVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCrearVehiculoActionPerformed
        // TODO add your handling code here:
        jifCrearVehiculo.repaint();
        jifCrearVehiculo.show();
        jcbCVCasco.setEnabled(false);
        jcbCVExtras.setEnabled(false);
        spnCVCapFurg.setEnabled(false);
        validarCrearVehiculo();

        if (jifCrearVehiculo.isIcon())
        {
            try
            {
                jifCrearVehiculo.setMaximum(true);
            }
            catch (PropertyVetoException ex)
            {
                Logger.getLogger(MdiVehiculos.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_mnuCrearVehiculoActionPerformed

    private void jcbCVFutgoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbCVFutgoActionPerformed
        validarCrearVehiculo();
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbCVFutgoActionPerformed

    private void jcbCVMotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbCVMotoActionPerformed
        validarCrearVehiculo();
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbCVMotoActionPerformed

    private void jcbCVCocheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbCVCocheActionPerformed
        validarCrearVehiculo();
    }//GEN-LAST:event_jcbCVCocheActionPerformed

    private void btnCVCrearVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCVCrearVehiculoActionPerformed
        if (txtCVMatricula.getText() == null || txtCVMatricula.getText().compareTo("") == 0)
        {
            JOptionPane.showMessageDialog(this, "Debe escribir la matricula del vehículo");
        }
        else if (txtCVKm.getText() == null || txtCVKm.getText().compareTo("") == 0)
        {
            JOptionPane.showMessageDialog(this, "Debe escribir el kilometraje del vehículo");
        }
        else if (txtCVValorAlquiler.getText() == null || txtCVValorAlquiler.getText().compareTo("") == 0)
        {
            JOptionPane.showMessageDialog(this, "Ingrese el valor del alquiler");
        }
        else if (!jcbCVMoto.isSelected() && !jcbCVFutgo.isSelected() && !jcbCVCoche.isSelected())
        {
            JOptionPane.showMessageDialog(this, "Debe seleccionar el tipo de vehículo");
        }
        else
        {
            if (jcbCVMoto.isSelected() == true)
            {
                Moto moto = new Moto(txtCVMatricula.getText(),
                        Integer.parseInt(txtCVKm.getText()),
                        jcbDistponible.isSelected(), Double.parseDouble(txtCVValorAlquiler.getText()),
                        jcbCVCasco.isSelected());
                try
                {
                    gestionVehiculo.adicionarVehiculo(moto);
                    llenarMotos();
                    JOptionPane.showMessageDialog(this, "Vehículo creado");

                }
                catch (VehiculosExcepcion ex)
                {
                    JOptionPane.showMessageDialog(this, ex.getMessage(), "Error al crear el vehiculo", 0);
                }
                txtCVKm.setText("");
                txtCVMatricula.setText("");
                txtCVValorAlquiler.setText("");
                jcbDistponible.setSelected(false);
                jcbCVMoto.setSelected(false);
                jcbCVCasco.setSelected(false);
            }
            else if (jcbCVCoche.isSelected() == true)
            {
                Coche coch = new Coche(txtCVMatricula.getText(), Integer.parseInt(txtCVKm.getText()), jcbDistponible.isSelected(), Double.parseDouble(txtCVValorAlquiler.getText()));
                try
                {
                    gestionVehiculo.adicionarVehiculo(coch);
                    llenarCoches();
                    JOptionPane.showMessageDialog(this, "Vehículo creado");

                }
                catch (VehiculosExcepcion ex)
                {
                    JOptionPane.showMessageDialog(this, ex.getMessage(), "Error al crear el vehiculo", 0);
                }
                txtCVKm.setText("");
                txtCVMatricula.setText("");
                txtCVValorAlquiler.setText("");
                jcbDistponible.setSelected(false);
                jcbCVCoche.setSelected(false);
                jcbCVExtras.setSelected(false);
            }

            else if (jcbCVFutgo.isSelected() == true)
            {
                Furgoneta furgoneta = new Furgoneta(txtCVMatricula.getText(),
                        Integer.parseInt(txtCVKm.getText()),
                        jcbDistponible.isSelected(),
                        Double.parseDouble(txtCVValorAlquiler.getText()));
                try
                {

                    gestionVehiculo.adicionarVehiculo(furgoneta);
                    llenarFurgonetas();
                    JOptionPane.showMessageDialog(this, "Vehículo creado");

                }
                catch (VehiculosExcepcion ex)
                {
                    JOptionPane.showMessageDialog(this, ex.getMessage(), "Error al crear el vehiculo", 0);
                }
                txtCVKm.setText("");
                txtCVMatricula.setText("");
                txtCVValorAlquiler.setText("");
                jcbDistponible.setSelected(false);
                jcbCVFutgo.setSelected(false);
                spnCVCapFurg.setValue(0);
            }

        }
    }//GEN-LAST:event_btnCVCrearVehiculoActionPerformed

    private void spnCVCapFurgStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnCVCapFurgStateChanged

    }//GEN-LAST:event_spnCVCapFurgStateChanged

    private void jcbCVCascoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbCVCascoActionPerformed

    }//GEN-LAST:event_jcbCVCascoActionPerformed

    private void jcbCVExtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbCVExtrasActionPerformed

    }//GEN-LAST:event_jcbCVExtrasActionPerformed

    private void txtCVKmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCVKmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCVKmActionPerformed

    private void txtCVMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCVMatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCVMatriculaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        jifCrearUsuario.repaint();
        jifCrearUsuario.show();
        if (jifCrearUsuario.isIcon())
        {
            try
            {
                jifCrearUsuario.setMaximum(true);
            }
            catch (PropertyVetoException ex)
            {
                Logger.getLogger(MdiVehiculos.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtCUIdentificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCUIdentificacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCUIdentificacionActionPerformed

    private void cboxTipoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxTipoUsuarioActionPerformed
        // TODO add your handling code here:  if (cboxTipoUsuario.getSelectedItem()=="Seleccionar"){
            if (cboxTipoUsuario.getSelectedItem().toString().equals("Client"))
            {
                txtCUCorreoElectronico.setEnabled(false);
                txtCUContrasenia.setEnabled(false);
            }
            else
            {
                txtCUContrasenia.setEnabled(true);
                txtCUCorreoElectronico.setEnabled(true);
            }
    }//GEN-LAST:event_cboxTipoUsuarioActionPerformed

    private void btnCrearUsrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearUsrActionPerformed
        // TODO add your handling code here:
        gestionUsuario.getTipoUsuarios();
        TipoUsuario[] tipos;

        if (cboxTipoUsuario.getSelectedItem().toString().equals("Adm") || cboxTipoUsuario.getSelectedItem().toString().equals("Usr"))
        {
            if (txtCUNombre.getText() == null || txtCUNombre.getText().compareTo("") == 0)
            {
                JOptionPane.showMessageDialog(this, "Debe escribir su nombre", "Datos Faltantes", 2);
            }
            else if (txtCUIdentificacion.getText() == null || txtCUIdentificacion.getText().compareTo("") == 0)
            {
                JOptionPane.showMessageDialog(this, "Debe escribir su identificacion", "Datos Faltantes", 2);
            }
            else if (txtCUCorreoElectronico.getText() == null || txtCUCorreoElectronico.getText().compareTo("") == 0)
            {
                JOptionPane.showMessageDialog(this, "Debe escribir un correo electronico", "Datos Faltantes", 2);
            }
            else if (txtCUContrasenia.getText() == null || txtCUContrasenia.getText().compareTo("") == 0)
            {
                JOptionPane.showMessageDialog(this, "Debe escribir una contraseña", "Datos Faltantes", 2);
            }
            else
            {

                String codigo = cboxTipoUsuario.getSelectedItem().toString().toLowerCase();
                byte numTipo = leer.convertirUsuario(codigo);
                tipos = gestionUsuario.getTipoUsuarios();
                Usuario usr = new Usuario(txtCUIdentificacion.getText(),
                        txtCUNombre.getText(),
                        tipos[numTipo],
                        txtCUCorreoElectronico.getText(),
                        txtCUContrasenia.getText());

                try
                {
                    gestionUsuario.agregarUsuario(usr);
                    pintarUsuarios();
                    llenarTablaClientes();
                    txtCUNombre.setText("");
                    txtCUIdentificacion.setText("");
                    txtCUCorreoElectronico.setText("");
                    txtCUContrasenia.setText("");
                }
                catch (VehiculosExcepcion ex)
                {
                    JOptionPane.showMessageDialog(this,
                        ex.getMessage(), "error en el usuario", 0);
                }
            }
        }
        else
        {
            if (txtCUNombre.getText() == null || txtCUNombre.getText().compareTo("") == 0)
            {
                JOptionPane.showMessageDialog(this, "Debe escribir su nombre", "Datos Faltantes", 2);
            }
            else if (txtCUIdentificacion.getText() == null || txtCUIdentificacion.getText().compareTo("") == 0)
            {
                JOptionPane.showMessageDialog(this, "Debe escribir su identificacion", "Datos Faltantes", 2);
            }
            //Crear cliente
            Cliente cliente = new Cliente(txtCUIdentificacion.getText(),
                                          txtCUNombre.getText());
            try
            {
                gestionUsuario.agregarCliente(cliente);
                pintarUsuarios();
                llenarTablaClientes();
                txtCUNombre.setText("");
                txtCUIdentificacion.setText("");
                txtCUCorreoElectronico.setText("");
                txtCUContrasenia.setText("");
            }
            catch (VehiculosExcepcion ex)
            {
                JOptionPane.showMessageDialog(this,
                    ex.getMessage(), "error en el cliente", 0);
            }

        }
    }//GEN-LAST:event_btnCrearUsrActionPerformed

    private void btnDescargarUsuariosPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescargarUsuariosPDFActionPerformed
        // TODO add your handling code here:
        try
        {

            CrearPDF usuarioPDF = new CrearPDF();
            usuarioPDF.crearDocumentoPdfUsuarios("./src/listaUsuarios.pdf", gestionUsuario.getUsuarios());
            usuarioPDF.abrirDocumento("./src/listaUsuarios.pdf");
        }
        catch (Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_btnDescargarUsuariosPDFActionPerformed

    private void mnuDescargarVehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDescargarVehiculosActionPerformed
        // TODO add your handling code here:
           try
        {
            // TODO add your handling code here:
            CrearPDF vehiculoPDF = new CrearPDF();
            vehiculoPDF.crearDocumentoPdfVehiculos("./src/pdfs/tabla.pdf", gestionVehiculo.getVehiculos());
            vehiculoPDF.abrirDocumento("./src/pdfs/tabla.pdf");
        }
        catch (Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_mnuDescargarVehiculosActionPerformed
    /**
     * @param args the command line arguments
     */
    
    public static void main (String args[]) {
        /*set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MdiVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MdiVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MdiVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MdiVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MdiVehiculos().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlquilar;
    private javax.swing.JButton btnCVCrearVehiculo;
    private javax.swing.JButton btnCalcularAlquiler;
    private javax.swing.JButton btnCrearUsr;
    private javax.swing.JButton btnDescargarUsuariosPDF;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JComboBox<String> cboxTipoUsuario;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateDevolucionAlquiler;
    private com.toedter.calendar.JDateChooser jDateEntregaAlquiler;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JCheckBox jcbCVCasco;
    private javax.swing.JCheckBox jcbCVCoche;
    private javax.swing.JCheckBox jcbCVExtras;
    private javax.swing.JCheckBox jcbCVFutgo;
    private javax.swing.JCheckBox jcbCVMoto;
    private javax.swing.JCheckBox jcbDistponible;
    private javax.swing.JInternalFrame jifAlquilar;
    private javax.swing.JInternalFrame jifCoches;
    private javax.swing.JInternalFrame jifCrearUsuario;
    private javax.swing.JInternalFrame jifCrearVehiculo;
    private javax.swing.JInternalFrame jifFurgonetas;
    private javax.swing.JInternalFrame jifListadoGeneralVehiculos;
    private javax.swing.JInternalFrame jifLogin;
    private javax.swing.JInternalFrame jifMotos;
    private javax.swing.JInternalFrame jifUsuarios;
    private javax.swing.JInternalFrame jifmVehiculosAlquilados;
    private java.awt.Label label10;
    private java.awt.Label label11;
    private java.awt.Label label12;
    private java.awt.Label label19;
    private java.awt.Label label20;
    private java.awt.Label label21;
    private java.awt.Label label22;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private java.awt.Label label9;
    private java.awt.Label lblName;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem mnuAlquilarVehiculo;
    private javax.swing.JMenu mnuArchivo;
    private javax.swing.JMenuItem mnuCerrarSesion;
    private javax.swing.JMenuItem mnuCrearUsuarios;
    private javax.swing.JMenuItem mnuCrearVehiculo;
    private javax.swing.JMenuItem mnuDescargarVehiculos;
    private javax.swing.JMenuItem mnuListaCoches;
    private javax.swing.JMenuItem mnuListaFurgonetas;
    private javax.swing.JMenuItem mnuListaMotos;
    private javax.swing.JMenuItem mnuListarUsuarios;
    private javax.swing.JMenuItem mnuSalir;
    private javax.swing.JMenu mnuVehiculos;
    private javax.swing.JMenuItem mnuVehiculosAlquilados;
    private javax.swing.JSpinner spnCVCapFurg;
    private javax.swing.JTable tbListadoGeneral;
    private javax.swing.JTable tblCliente;
    private javax.swing.JTable tblCoches;
    private javax.swing.JTable tblFurgonetas;
    private javax.swing.JTable tblMotos;
    private javax.swing.JTable tblUsuarios;
    private javax.swing.JTable tblVehiculosAlquilados;
    private javax.swing.JTextField txtCUContrasenia;
    private javax.swing.JTextField txtCUCorreoElectronico;
    private javax.swing.JTextField txtCUIdentificacion;
    private javax.swing.JTextField txtCUNombre;
    private javax.swing.JTextField txtCVKm;
    private javax.swing.JTextField txtCVMatricula;
    private javax.swing.JTextPane txtCVValorAlquiler;
    private javax.swing.JTextPane txtClienteSeleccionado;
    private javax.swing.JPasswordField txtContrasenia;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtMatriculaSelec;
    private javax.swing.JTextField txtOpcionesExtras;
    // End of variables declaration//GEN-END:variables

}
